package lk.customs.rms.enums;

public enum AppPermission {
    CREATE_DOCUMENT,
    VIEW_PUBLIC_DOCUMENT,
    VIEW_PRIVATE_DOCUMENT,
    VIEW_OWN_CREATED_DOCUMENTS,
    VIEW_ALL_DOCUMENTS,
    EDIT_DOCUMENT_DETAILS,
    ADD_REMARK,
    FORWARD_DOCUMENT,
    FORWARD_PUBLIC,
    FORWARD_PRIVATE,
    CHANGE_DOCUMENT_VISIBILITY,
    RETURN_DOCUMENT,
    APPROVE_DOCUMENT,
    REJECT_DOCUMENT,
    ISSUE_DOCUMENT,
    REOPEN_DOCUMENT,
    UPLOAD_ATTACHMENT,
    DELETE_ATTACHMENT,
    VIEW_ALL_HISTORY,
    VIEW_LOGS,
    VIEW_SENT_MESSAGES
}