package lk.customs.rms.enums;

public enum AppPermission {
    CREATE_DOCUMENT,
    EDIT_DOCUMENT_DETAILS,
    ADD_REMARK,
    FORWARD_DOCUMENT,
    FORWARD_PUBLIC,
    FORWARD_PRIVATE,
    RETURN_DOCUMENT,
    APPROVE_DOCUMENT,
    REJECT_DOCUMENT,
    ISSUE_DOCUMENT,
    REOPEN_DOCUMENT,
    UPLOAD_ATTACHMENT,
    DELETE_ATTACHMENT,
    VIEW_ALL_HISTORY,
    VIEW_LOGS
}