spring.application.name=rms-backend

server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/customs_rms?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Upload settings (✅ external folder recommended)
# Windows example:
app.upload-dir=C:/customs_uploads

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=25MB
spring.servlet.multipart.max-request-size=25MB

# JWT settings
app.jwt.secret=Y3VzdG9tcy1ybXMtand0LXNlY3JldC1rZXktMjAyNi1jaGFuZ2UtbWU=
app.jwt.expiration-ms=28800000
